export const FETCH_ALL_TICKER_REQUEST = "FETCH_ALL_TICKER_REQUEST";
export const FETCH_ALL_TICKER_SUCCESS = "FETCH_ALL_TICKER_SUCCESS";
export const FETCH_ALL_TICKER_FAILURE = "FETCH_ALL_TICKER_FAILURE";